apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ubuntu-ds
  labels:
spec:
  selector:
    matchLabels:
      app: ubuntu-ds-pod
  template:
    metadata:
      labels:
        app: ubuntu-ds-pod
    spec:
      containers:
      - image: ubuntu
        name: ubuntu-cont
        tty: true
        stdin: true

